### ISSUE TITLE
add new status NOTCHANGED

### ISSUE THREAD

**Issue by tantra35** [moira-alert/worker#1]
This status will be usful in custom python expressions, when value of trigger nee some of "death" zone. For example if we have 50 as value of trigger, when wher value reach 49.5 оor 50.5 we can return NOTCHANGED, and trigger doesn't switch it state

**Comment by gmlexx** [comment]
Trigger's expression calculates the new trigger state.
NOTCHANGED state blur existing conception.
But if you need some previous value and current trigger state to calculate new trigger state, we can easily add a few reserved variables like "t1, warn_value, error_value" available to use in expression.
For example, PREV_STATE if abs(t1 - prev_t1) < 1 else ERROR

Or may be your case can be solved in existing expression syntax. Can you give more details about your case?

**Comment by tantra35** [comment]
I thik about this, you suggestion is better then NOTCHANGED, so i agree with you concept. For now we have some value with small fluctuations, around some const value(for example 50), so values can be 49.5. 49.9. 50.1 ans so on, and at each change trigger is switch it state

**Comment by gmlexx** [comment]
Why standard derivative, movingAverage, etc graphite functions doesn't satisfy you?

**Comment by tantra35** [comment]
this values was get from this transformations

**Comment by gmlexx** [comment]
Ok, why it is not enough?

**Comment by tantra35** [comment]
Because value can change on small range, and PREV_STATE allow describes the band of allowed values, WARN,OK,EROR, doesn't allow this

PS: russian version
Попытаюсь обрисовать ситуацию на родном языке. Вот предположим у нас есть всплеск некоей величины, а потом плавный её спуск до приемлемого значения, в момент когда величина пересекает пороговое значение триггера, она может колебаться вокруг этого порогового значения какое то время, в результате мы имеем ложные срабатывания: "включено", "выключено" в этот момент, введение же полосы пропускания позволит имхо избежать этих срабатываний. Мы очень долго пытались побороть такое поведение в zabbix, но без особых успехов, более менее помогали эскалации, у мойры же её довольно простая архитектура позволяет добавить подобное поведение очень просто и дешево

**Comment by gmlexx** [comment]
Ok, check please that I understand right.

Problem:
Value has changed and then started fluctuation around new value.
This fluctuation could lead to trigger fatigue (unwanted state changing)

Solution:
Add PREV_STATE variable to allow expression check, that derivative of value is small and not change state.

**Comment by tantra35** [comment]
Yes that's right. Or you may extend custom exresssion feature not only write python generator expression, but fully python code, in this situation moira will be like bosun(https://bosun.org/), but i doesn't think that it is a good idea.

**Comment by gmlexx** [comment]
Add PREV_STATE in @a7d2af5
