### ISSUE TITLE
Missed alert

### ISSUE THREAD

**Issue by beevee** [moira-alert/worker#15]
For the following expression:
`alias(summarize(maxSeries(divideSeries(KE.banana.jvm.*.heap.HeapMemoryUsage_used, minSeries(KE.banana.jvm.*.heap.HeapMemoryUsage_max))), '10min', 'max'), 'jvm heap moving max')`

Moira missed an alert today. Last event is on May, 5th:
![2016-05-10_18-53-45](https://cloud.githubusercontent.com/assets/1009675/15148860/1a69dcc6-16e9-11e6-8ea3-a949bbe585a5.png)

And here is a graph from today, clearly over the limits at 14:40 MSK and 15:00..15:20 MSK:
![render](https://cloud.githubusercontent.com/assets/1009675/15148930/72517d9a-16e9-11e6-8208-2012239ad0e9.png)

**Comment by gmlexx** [comment]
Highest values are related to one specific node.
As you can see on dashboard, there is some lack of values between top values and previous values.
My assumption is that highest values came to moira after trigger check was performed.
It would not be a problem if no other values existed, but there were other values from other hosts, so maxSeries and minSeries functions were evaluated and values that were late - missed.

![screen shot 2016-05-10 at 22 10 45](https://cloud.githubusercontent.com/assets/1112318/15159259/8efae770-16fc-11e6-893a-a3abddee453d.jpg)

**Comment by gmlexx** [comment]
In case if there is no alerts since last check, checker now has a 2 min gap by default, that allows it to account late metric points and generate events for them.

**Comment by gmlexx** [comment]
Let's wait until merge with master, before close this issue :)

**Comment by gmlexx** [comment]
Merged with master.
