### ISSUE TITLE
Artifacts in metrics

### ISSUE THREAD

**Issue by beevee** [moira-alert/worker#16]
![moira - google chrome 2016-05-11 11 11 17](https://cloud.githubusercontent.com/assets/1009675/15177839/0d3762b6-1794-11e6-9614-c9b4baac09d3.jpg)

Metric with wildcards did not disappear after real data had started coming. A little detail: real data started coming a long time after trigger had been created - maybe that's the reason.

**Comment by gmlexx** [comment]
Yes, exactly this reason.

**Comment by beevee** [comment]
So, wontfix? :)

**Comment by gmlexx** [comment]
Not so fast, let me have a look, may be we can fix this.
