### ISSUE TITLE
/api/trigger/page return empty list while triggers don't checked

### ISSUE THREAD

**Issue by Slach** [moira-alert/worker#21]
latest release moira-worker 1.2.0 and moira-web 1.1.0 not worked properly together

GET /api/trigger/
return list of triggers
see http://pastebin.com/h4JikAkB

but  GET /api/trigger/page?p=0&size=20 return empty trigger list and moira
<pre>
{"total":0,"list":[],"page":0,"size":20}
</pre>

**Comment by gmlexx** [comment]
/api/trigger/page?p=0&size=20 need some time for triggers check.
New check will assign a "score" for trigger. Worst trigger state gets highest score.
So, /page returns only scored triggers.

**Comment by Slach** [comment]
it's bad use case
User except show trigger in trigger list after create trigger shortly
