### ISSUE TITLE
can't uninstall over pip

### ISSUE THREAD

**Issue by Slach** [moira-alert/worker#22]
pip uninstall moira-worker
return 
<pre>
Can't uninstall 'moira-worker'. No files were found to uninstall.
</pre>

**Comment by gmlexx** [comment]
Works on my machine :)
May be this is the result of manual packages deletion from pythons/site-packages?
Anyway need more information about environment.

**Comment by Slach** [comment]
too old pip 1.5.4  installed over python-pip, i try update pip manually and reinstall moira-worker 1.2.0 over 1.1.14

**Comment by AlexAkulov** [comment]
Problem solved after pip update?

**Comment by Slach** [comment]
yep, 
easy_install -U pip
ln -s /usr/local/bin/pip /usr/bin/pip
