### ISSUE TITLE
Stop all checks if moira-cache is not working

### ISSUE THREAD

**Issue by beevee** [moira-alert/worker#3]
When moira-cache fails, all metrics eventually drop into NODATA state, spamming all users with unnecessary notifications.

In fact, only Moira administrators should notice that Moira is not working properly.

**Comment by gmlexx** [comment]
It seems, that we need to introduce some trigger escalation process, like if system trigger OK, then process ordinary triggers, otherwise notify admins only.

**Comment by beevee** [comment]
It happened again today. Network interface failed and Moira was not receiving any data for 10+ minutes. Again, everybody received a ton of irrelevant notifications.

**Comment by beevee** [comment]
Looks very much a bug to me. If something happens to Moira and we are not able to fix it faster than 10 minutes, *inevitably* every metric will have a OK-NODATA-OK event. We just don't have any mechanisms to prevent it.

**Comment by gmlexx** [comment]
Add stop_checking_interval settings to prevent launch nodata checks if none metrics receiving
@ac95c69
