### ISSUE TITLE
Failed to perform triggers check

### ISSUE THREAD

**Issue by avinchakov** [moira-alert/worker#44]
I get error:
`2017-01-19T11:26:59+0300 [moira.logs#info] Checking trigger 6b8cf6db-97f7-447c-abef-f70ec8ae766f
2017-01-19T11:26:59+0300 [moira.logs#info] Writing new event: {'timestamp': 1484812019, 'metric': u'Test_Vlan.rx', 'value': nan, 'state': 'OK', 'trigger_id': u'6b8cf6db-97f7-447c-abef-f70ec8ae766f', 'old_state': u'NODATA'}
2017-01-19T11:26:59+0300 [moira.logs#error] Trigger check failed: Invalid Nan value when encoding double
2017-01-19T11:26:59+0300 [moira.logs#info] Writing new event: {'old_state': u'OK', 'timestamp': 1484814419, 'state': 'EXCEPTION', 'metric': None, 'trigger_id': u'6b8cf6db-97f7-447c-abef-f70ec8ae766f'}
2017-01-19T11:26:59+0300 [moira.logs#error] Failed to perform triggers check: Invalid Nan value when encoding double`

data in a metrics Test_Vlan.rx are.

**Comment by avinchakov** [comment]
`aliasSub(
    cisco.fw.snmp.if_octets.Adaptive_Security_Appliance_*{Vlan,Outside}*_interface.rx,
    "^[^']*'(
        [^']*Vlan|Outside)'.*$",
    "\1.rx")`

the trigger didn't work so far there was a big traffic as soon as the traffic normalize - the trigger started working

П.С. пытаюсь настроить алерты на большой трафик, вчера поставил его, было все ок, пока не пошел трафик больше. Вот отрезок из метрики:
`Thu Jan 19 11:35:00 2017	20530.647028
Thu Jan 19 11:35:30 2017	8221.495621
Thu Jan 19 11:36:00 2017	3043.316689
Thu Jan 19 11:36:30 2017	11021.311253
Thu Jan 19 11:37:00 2017	4636.799361
Thu Jan 19 11:37:30 2017	12721.321648
Thu Jan 19 11:38:00 2017	20595.896768
Thu Jan 19 11:38:30 2017	19708.094672
Thu Jan 19 11:39:00 2017	3871.184198
Thu Jan 19 11:39:30 2017	2879.361205
Thu Jan 19 11:40:00 2017	46584.924546
Thu Jan 19 11:40:30 2017	11354.932133
Thu Jan 19 11:41:00 2017	2896.699468
Thu Jan 19 11:41:30 2017	4779.175268
Thu Jan 19 11:42:00 2017	5899.025248
Thu Jan 19 11:42:30 2017	20296.716322
Thu Jan 19 11:43:00 2017	22183.365537
Thu Jan 19 11:43:30 2017	2967.129914
Thu Jan 19 11:44:00 2017	13819.579750
Thu Jan 19 11:44:30 2017	3029.737704
Thu Jan 19 11:45:00 2017	4238.848891
Thu Jan 19 11:45:30 2017	3678.339492
Thu Jan 19 11:46:00 2017	3303.236984
Thu Jan 19 11:46:30 2017	3114.108571
Thu Jan 19 11:47:00 2017	3743.673017
Thu Jan 19 11:47:30 2017	2999.249490
Thu Jan 19 11:48:00 2017	20546.736326
Thu Jan 19 11:48:30 2017	3026.457487
Thu Jan 19 11:49:00 2017	3395.407264
Thu Jan 19 11:49:30 2017	2946.268193
Thu Jan 19 11:50:00 2017	3179.250655`

Не работал пока были большие значения.

**Comment by gmlexx** [comment]
Is it possible, that your actual values are higher, than python float(str) function can convert?

**Comment by avinchakov** [comment]
I don't know... I can only give you whisper-fetch output from this metric.

**Comment by gmlexx** [comment]
Try to run checker from command line to check problem trigger by id, it will output fetched values and try to read all metric values from redis database for problem metric when problem happen again.

**Comment by avinchakov** [comment]
Thank you, I will try it.
