### ISSUE TITLE
Remind users of broken triggers

### ISSUE THREAD

**Issue by beevee** [moira-alert/worker#5]
In a healthy working environment all triggers should be in OK or sometimes WARN state. Trigger in a ERROR or NODATA state is a critical situation and requires immediate fix.

But in reality, Moira users tend to ignore triggers that switched to ERROR or NODATA state several days ago. These triggers just hang around the top of the list, drawing attention from real problems. We should force users to fix broken triggers or delete them.

I propose to send a notification every 24h for every trigger in ERROR or NODATA state:

> ERROR Trigger name [tag1][tag2]
> DevOps.system.cpu.load = 99 (ERROR for 48 hours)
> ...
> 
> ERROR and NODATA are critical conditions that require immediate attention. Some of your metrics have been in this state for days. If this is a non-critical issue, you should make it a WARN or OK.

**Comment by gmlexx** [comment]
:thumbsup:

**Comment by gmlexx** [comment]
Added in @2b84590
