### ISSUE TITLE
Old metrics did not disappear after changing pattern

### ISSUE THREAD

**Issue by beevee** [moira-alert/worker#8]
![2016-04-11_13-41-13](https://cloud.githubusercontent.com/assets/1009675/14421456/99a0f388-fff3-11e5-9740-0d61b93e4b54.png)

(see screenshot)

After changing function params from 5min to 3min, old metrics did not disappear. As you can see, the change was a long time ago, on March, 28th.

**Comment by gmlexx** [comment]
Fixed in @403588a
